### ISSUE TITLE
Request: extract channel number and call sign from single display-name

### ISSUE THREAD

**Issue by CoolCanuck** [rickz0rz/prevuecommander#1]
Hi

Could you please have an option of extracting channel number and call sign from single display-name such as 6 CBURN = channel 6 callsign CBURN? Attached is an xml example

This will allow more epg sources such as m3u4u.com :)
[EPG-Guide-20220324142340.zip](https://github.com/rickz0rz/prevuecommander/files/8344367/EPG-Guide-20220324142340.zip)

Thank you very very much in advance

**Comment by rickz0rz** [comment]
Resolved in recent commit.
