### ISSUE TITLE
Request: Playbook option to not send program descriptions (titles only)

### ISSUE THREAD

**Issue by CoolCanuck** [rickz0rz/prevuecommander#4]
It would be appreciated if there was a playbook option to only send titles (not the entire program description), significantly reducing the time it takes to send data (some people do not have Movies tagged in their xmltv and so descriptions are never used)

**Comment by rickz0rz** [comment]
If you don't have any data tagged as a movie, then the text in the guide shouldn't ever have the movie description as part of the data. See here https://github.com/rickz0rz/prevuecommander/blob/main/PrevueCommander.XmlTv/XmlTvCore.cs#L137 for the exact line. If you are seeing that, please let me know with an example!
